# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Self-Amusement Park
email: bryanstearns@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://selfamusementpark.com" # the base hostname & protocol for your site
timezone: "America/Los_Angeles"

gems:
- jekyll-paginate

twitter_username: bryanstearns
github_username:  bryanstearns

# Build settings
# lsi: true
markdown: kramdown
excerpt_separator: <!--more-->
permalink: :title
paginate: 12
exclude:
- old
- Gemfile
- Gemfile.lock
include:
- .nojekyll

defaults:
  -
    scope:
      path: "" # all files
      type: "posts"
    values:
      layout: "post"
